## Reshaping Arrays

In [1]:
import numpy as np

In [2]:
np.arange(1, 15).shape

(14,)

In [3]:
array_2d = np.arange(1, 15).reshape(2, 7)
array_2d

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [4]:
array_1d = array_2d.reshape(14)
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Assignment
**Create a 5 x 5 array with numbers from 1 to 25**

In [5]:
np.arange(1, 26).reshape(5, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**Create a 2 x 3 array with all numbers having value `100`**

In [6]:
# Hint: Use `np.full()` function

In [7]:
np.full(shape=(2, 3), fill_value=100)

array([[100, 100, 100],
       [100, 100, 100]])

## Indexing in Arrays

### 1D Array

In [8]:
x = np.arange(3, 10, 2)
x

array([3, 5, 7, 9])

In [9]:
# Extract the last value in the array
x[-1]

np.int64(9)

In [10]:
x[0]

np.int64(3)

## 2D Array

In [11]:
y = np.arange(3, 13).reshape(2, 5)
y

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12]])

#### Syntax
```python
variable/object[row_idx, col_idx]
```

In [12]:
y[1, 2]

np.int64(10)

In [13]:
y[1, 4]

np.int64(12)

In [14]:
y[0, 0]

np.int64(3)

### Fancy Indexing

Fancy Indexing is used to extract any index in any order.

In [15]:
x

array([3, 5, 7, 9])

In [18]:
x[[1, 3]]

array([5, 9])

In [19]:
y

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12]])

In [20]:
y[[1], [1, 3]]

array([ 9, 11])

In [21]:
y[:, [1, 2, 4]]

array([[ 4,  5,  7],
       [ 9, 10, 12]])

### Boolean Indexing

**Boolean Operators:**

* `&` - `and` operator
* `|` - `or` operator
* `~` - `not` operator

In [22]:
grades = np.array([55, 40, 88, 99, 25, 10, 100])

In [24]:
(grades > 80) & (grades < 100)

array([False, False,  True,  True, False, False, False])

In [26]:
boolean_array = grades > 50  # Boolean Array
boolean_array

array([ True, False,  True,  True, False, False,  True])

In [27]:
~boolean_array

array([False,  True, False, False,  True,  True, False])

In [28]:
grades[boolean_array]

array([ 55,  88,  99, 100])

## Slicing in Arrays

### 1D Array

In [29]:
x = np.arange(10, 21)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [30]:
x[3:9]

array([13, 14, 15, 16, 17, 18])

In [31]:
x[9:3]

array([], dtype=int64)

In [32]:
x[5:2:-1]

array([15, 14, 13])

### 2D Array

In [33]:
k = np.arange(9).reshape(3, 3)
k

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
k[1:3, 0:2]

array([[3, 4],
       [6, 7]])

In [35]:
k[1:3, 1:3]

array([[4, 5],
       [7, 8]])

In [36]:
k[1:3, 1]

array([4, 7])

In [37]:
k[0]

array([0, 1, 2])

##  Mathematical Operators in Arrays

In [38]:
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [39]:
x * 2

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [40]:
 x + 2

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [41]:
x ** 2  # Exponentiation

array([100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400])

In [ ]:
y

In [ ]:
s = np.arange(10, 20).reshape(2, 5)
s

In [ ]:
y + s

In [ ]:
y * s

In [ ]:
y  # 2 x 5 array

In [ ]:
t = np.arange(40, 50).reshape(5, 2)  # 5 x 2 array
t

In [ ]:
y @ t  # @ - Matrix Multiplication

In [ ]:
t @ y

In [ ]:
# Try with 3 x 2 array matrix multiply 2 x 5

In [ ]:
y

In [ ]:
y.sum()

In [ ]:
y.sum(axis=1)  # Row-wise sum

In [ ]:
y.sum(axis=0)  # Column-wise sum

In [ ]:
y.mean(axis=1)

In [ ]:
y.mean(axis=0)

## Commonly used Functions

In [ ]:
a = np.array([1, 2, 3])
a

In [ ]:
a.cumsum()

In [ ]:
x

In [ ]:
x.min()  # method

In [ ]:
np.min(x)  # function

In [ ]:
np.argmin(x)

In [ ]:
np.arm