# NumPy

NumPy stands for **Numerical Python**.

The core object of NumPy is **arrays**. The NumPy array is faster than Python's List object.

NumPy's array can store only one data type. Mixed data types are automatically
type-casted.

### Demo: Python List vs NumPy Array speed test

In [2]:
list(range(1, 10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list_object = list(range(1, 1_00_001))  # Creating a list of 1,00,000 elements
len(list_object)

100000

In [5]:
%%timeit

double = []   # Multiplying every element in `list_object` by 2
for num in list_object:
    result = num * 2
    double.append(result)

9.96 ms ± 727 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
import numpy as np

In [8]:
numpy_object = np.arange(1, 1_00_001)
len(numpy_object)

100000

In [11]:
%%timeit

numpy_object * 2

60.5 μs ± 8.49 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [9]:
[1, 2, 3] * 2

[1, 2, 3, 1, 2, 3]

In [10]:
x = np.array([1, 2, 3])
x * 2

array([2, 4, 6])

## Create a NumPy array

In [12]:
import numpy as np

In [13]:
np.array?

Signature:
np.array(
    object,
    dtype=None,
    *,
    copy=True,
    order='K',
    subok=False,
    ndmin=0,
    ndmax=0,
    like=None,
)
Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      ndmax=0, like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    require

In [14]:
np.array([1, 2, 3, 4, 5])  # NumPy array object

array([1, 2, 3, 4, 5])

In [15]:
[1, 2, 3, 4, 5]   # List of object

[1, 2, 3, 4, 5]

In [22]:
np.array([1.0, 3, 4, 5, 8.2], dtype=np.float64)  # Try using np.int16, np.int64

array([1. , 3. , 4. , 5. , 8.2])

In [17]:
np.array([1.0, 2.0, 'a', 'b', 3, 5])

array(['1.0', '2.0', 'a', 'b', '3', '5'], dtype='<U32')

In [23]:
dir(np.array([]))

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',


In [24]:
scores = np.array([88, 55, 99, 100, 33])

In [25]:
scores.shape  # 1-dimensional array with 5 elements

(5,)

In [26]:
scores.size  # Number of elements in the array

5

In [27]:
scores.ndim  # Number of dimensions in the array

1

In [28]:
scores.dtype   # Data type of each element in the array

dtype('int64')

In [29]:
scores.min()  # Minimum value in the array

np.int64(33)

In [30]:
scores.max()  # Maximum value in the array

np.int64(100)

In [37]:
scores.sort()  # Sorts the values in the array in ascending order

In [32]:
scores

array([ 33,  55,  88,  99, 100])

In [36]:
scores[::-1] # Sorts the values in descending order, but gives a new object

array([100,  99,  88,  55,  33])

In [39]:
scores = scores[::-1]

In [40]:
scores

array([100,  99,  88,  55,  33])

In [35]:
scores.sort?

Signature: scores.sort(axis=-1, kind=None, order=None, *, stable=None)
Docstring:
a.sort(axis=-1, kind=None, order=None, *, stable=None)

Sort an array in-place. Refer to `numpy.sort` for full documentation.

Parameters
----------
axis : int, optional
    Axis along which to sort. Default is -1, which means sort along the
    last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort under the covers and, in general, the
    actual implementation will vary with datatype. The 'mergesort' option
    is retained for backwards compatibility.
order : str or list of str, optional
    When `a` is an array with fields defined, this argument specifies
    which fields to compare first, second, etc.  A single field can
    be specified as a string, and not all fields need be specified,
    but unspecified fields will still be used, in the order in which
    they come up in

In [43]:
scores

array([100,  99,  88,  55,  33])

In [41]:
scores.argmin() # Index of the maximum value

np.int64(4)

In [42]:
scores.argmax()  # Index of the minimum value

np.int64(0)

## Other ways to create NumPy array

In [46]:
np.linspace(start=1, stop=10, num=10)  # Create evenly spaced values between start and end (including)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [45]:
np.linspace?

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x00000268EB9FE5C0>
File:            d:\anaconda\envs\python_env\lib\site-packages\numpy\_core\function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to Fal

In [47]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [48]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [49]:
np.full?

Signature:
np.full(
    shape,
    fill_value,
    dtype=None,
    order='C',
    *,
    device=None,
    like=None,
)
Docstring:
Return a new array of given shape and type, filled with `fill_value`.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
fill_value : scalar or array_like
    Fill value.
dtype : data-type, optional
    The desired data-type for the array  The default, None, means
     ``np.array(fill_value).dtype``.
order : {'C', 'F'}, optional
    Whether to store multidimensional data in C- or Fortran-contiguous
    (row- or column-wise) order in memory.
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
     

In [54]:
np.full(shape=(8,), fill_value='data')

array(['data', 'data', 'data', 'data', 'data', 'data', 'data', 'data'],
      dtype='<U4')

## Creating 2D arrays

In [55]:
# Input: List of lists
temps = [[23.0, 25.0, 33.0], 
         [45.0, 28.0, 22.0],
         [33.5, 40.0, 22.5]]

In [58]:
temps_array = np.array(temps)
temps_array

array([[23. , 25. , 33. ],
       [45. , 28. , 22. ],
       [33.5, 40. , 22.5]])

In [61]:
temps_array.shape  # 3 rows and 3 columns

(3, 3)

In [62]:
temps_array.size  # Total number of elements: 9

9

In [63]:
temps_array.ndim  # Number of dimensions: 2

2

## Other ways to create 2D arrays

In [64]:
np.zeros?

Signature: np.zeros(shape, dtype=None, order='C', *, device=None, like=None)
Docstring:
zeros(shape, dtype=None, order='C', *, device=None, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in memory.
device : str, optional
    The device on which to place the created array. Default: ``None``.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` proto

In [65]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [66]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])